---
# tasks file for docker_container
- name: Create a network
  docker_network:
    name: "{{ docker_container_network }}"

- name: Deploy Docker Container
  docker_container:
    name: "{{ docker_container_instance_name }}"
    hostname: "{{ docker_container_instance_name }}"
    image: "{{ docker_container_docker_image }}"
    state: started
    restart: true
    restart_policy: always
    recreate: true
    networks_cli_compatible: true
    purge_networks: true
    ports:
      - "{{ docker_container_bind_port }}:{{ docker_container_container_port }}"
    networks:
      - name: "{{ docker_container_network }}"
  register: docker_container_status

- name: Debug
  debug:
    msg: "{{ docker_container_status.ansible_facts.docker_container['State']['Status'] }}"
  when: docker_container_status.ansible_facts.docker_container is defined
